src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Room $Location = null;

    #[ORM\Column]
    private ?bool $isCompleted = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLocation(): ?Room
    {
        return $this->Location;
    }

    public function setLocation(?Room $Location): static
    {
        $this->Location = $Location;

        return $this;
    }

    public function isIsCompleted(): ?bool
    {
        return $this->isCompleted;
    }

    public function setIsCompleted(bool $isCompleted): static
    {
        $this->isCompleted = $isCompleted;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('Location')
            ->add('isCompleted')
        ;   
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\TaskType;
use App\Form\TaskTypeCheck;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/task')]
class TaskController extends AbstractController
{
    #[Route('/', name: 'app_task_index', methods: ['GET', 'POST'])]
    public function index(Request $request, EntityManagerInterface $entityManager, TaskRepository $taskRepository): Response
    {   
        $tasks = $taskRepository->findAll();
        
        // if ($request->isMethod('POST')) {
            
            foreach ($tasks as $task) {
                $isCompleted = $request->request->get('isCompleted' . $task->getId(), false);
                $task->setIsCompleted($isCompleted);

                $entityManager->persist($task);
            
            }
            $entityManager->flush();
        // }
        return $this->render('task/index.html.twig', [
            'tasks' => $tasks,
        ]);
    }

    #[Route('/new', name: 'app_task_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($task);
            $entityManager->flush();

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_task_show', methods: ['GET'])]
    public function show(Task $task): Response
    {
        return $this->render('task/show.html.twig', [
            'task' => $task,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_task_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
        ]);
    }

    #[Route('/task/{id}', name: 'app_task_delete', methods: ['POST'])]
    public function delete(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$task->getId(), $request->request->get('_token'))) {
            $entityManager->remove($task);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn">Delete</button>
</form>

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block body %}
    <h1>Edit Task</h1>

    {{ include('task/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_task_index') }}">back to list</a>

        
    {{ include('task/_delete_form.html.twig') }}

{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task index{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
{% endblock %}

{% block body %}
    <h1 class="text-2xl text-center mt-10">Task index</h1>
    <form method="post">
    <table class="table w-3/4 text-sm text-left text-gray-500 dark:text-gray-400 mt-4 mx-auto">
        <thead class="text-l text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th class="px-6 py-3">Id</th>
                <th class="px-6 py-3">Name</th>
                <th class="px-6 py-3">Description</th>
                <th class="px-6 py-3">Location</th>
                <th class="px-6 py-3">isCompleted</th>
                <th class="px-6 py-3">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr class="bg-white border-b dark:bg-white-900 dark:border-gray-700 text-black">
                <td class="px-6 py-4">{{ task.id }}</td>
                <td class="px-6 py-4">{{ task.name }}</td>
                <td class="px-6 py-4">{{ task.description }}</td>
                <td class="px-6 py-4">{{ task.location }}</td>
                {# <td>
                {% if task.isCompleted %}   
                    <input type="checkbox" name="checkbox" checked disabled>
                    {% else %}
                        <input type="checkbox" name="checkbox">
                {% endif %}
                </td> #}
                <td class="px-6 py-4">
                    <input type="checkbox" id="isCompleted{{ task.id }}" name="isCompleted{{ task.id }}" 
                    {% if task.isCompleted %}checked{% endif %}>
                </td>
                <td class="px-6 py-4 font-bold">
                    <a href="{{ path('app_task_show', {'id': task.id}) }}">show</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>
                    {% endif %}
                    
                </td>
                
            </tr>
        {% else %}
            <tr class="px-6 py-4">
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
        <button type="submit" class="mx-auto block mt-5 font-bold">Save Changes</button>
    </form>
    {% if is_granted('ROLE_ADMIN') %}
    <div class="flex justify-center mt-5 font-bold">
        <a href="{{ path('app_task_new') }}">Create new</a>
    </div>
    {% endif %}
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Task{% endblock %}

{% block body %}
    <h1>Create new Task</h1>

    {{ include('task/_form.html.twig') }}

    <a href="{{ path('app_task_index') }}">back to list</a>
{% endblock %}

templates/task/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Task{% endblock %}

{% block body %}
    <h1>Task</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ task.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ task.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ task.description }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ task.location }}</td>
            </tr>
            <tr>
                <th>isCompleted</th>
                <td>{{ task.isCompleted }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_task_index') }}">back to list</a>
    
    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('app_task_edit', {'id': task.id}) }}">edit</a>

    {{ include('task/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}